- name: ping for connection
  hosts: loscalhost
  tasks:
    - ping:

- name: Sample playbook
  hosts: localhost
  tasks:
    - name: Print Hello World
      ansible.builtin.debug:
        msg: Hello World


